#include QMK_KEYBOARD_H


#define _LAYER0 0
#define _LAYER1 1
#define _LAYER2 2
#define _LAYER3 3
#define _LAYER4 4
#define _LAYER5 5
#define _LAYER6 6

enum custom_keycodes {
    LAYER0 = SAFE_RANGE,
    LAYER1,
    LAYER2,
    LAYER3,
    LAYER4,
    LAYER5,
    LAYER6,
};

 const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {

 [_LAYER0] = LAYOUT(
  KC_NO, KC_Q, KC_W, KC_E, KC_R, KC_T, KC_Y, KC_U, KC_I, KC_O, KC_P, KC_BSPC,
  KC_NO, CTL_T(KC_A), ALT_T(KC_S), KC_D, LT(5,KC_F), KC_G, KC_H, LT(4,KC_J), KC_K, ALT_T(KC_L), CTL_T(KC_SCLN), KC_NO,
  KC_NO, SFT_T(KC_Z), GUI_T(KC_X), KC_C, LT(6,KC_V), KC_B, KC_N, KC_M, KC_COMM, GUI_T(KC_DOT), SFT_T(KC_SLSH), KC_NO,
  KC_NO, KC_NO, KC_NO, KC_NO, LT(1,KC_INT5), CTL_T(KC_SPC), SFT_T(KC_SPC), LT(2,KC_INT4), KC_NO, KC_NO, KC_NO, KC_NO
  ),

[_LAYER1] = LAYOUT(
  KC_ESC, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_DEL,
  KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_GRV, KC_MINS, KC_EQL, KC_LBRC, KC_RBRC, KC_BSLS,
  KC_TRNS, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_TILD, KC_UNDS, KC_PLUS, KC_LCBR, KC_RCBR, KC_PIPE,
  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS,  KC_TRNS, KC_TRNS, KC_ENT, MO(3),  KC_LABK, KC_RABK, KC_QUES, KC_TRNS
  ),

[_LAYER2] = LAYOUT(
  KC_ESC, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_DEL,
  KC_TRNS, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_NO, KC_ENT,  
  KC_TRNS, KC_F6, KC_F7, KC_TRNS, KC_F9, KC_F10, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_F11, KC_F12,
  KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, MO(3), KC_ENT ,KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS
  ),


[_LAYER3] = LAYOUT(
  BL_TOGG, QK_BOOT, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO,
  KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_MS_L, KC_MS_D, KC_MS_U, KC_MS_R, KC_NO, KC_NO, 
  KC_NO, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_BTN1, KC_BTN2, KC_NO, KC_F11, KC_F12, KC_NO, 
  KC_NO, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_TRNS, KC_NO, KC_VOLD, KC_VOLU, KC_NO
  ),

[_LAYER4] = LAYOUT(
  KC_NO, KC_1, KC_2, KC_3, KC_4, KC_5, KC_NO, KC_NO, KC_ESC, KC_BSPC, KC_DEL,KC_NO,
  KC_NO, KC_6, KC_7, KC_8, KC_9, KC_0, KC_NO, KC_TRNS, KC_SPC, KC_LALT, KC_LCTL, KC_NO,
  KC_NO, KC_TAB, KC_TAB, KC_SPC, KC_ENT, KC_ENT, KC_NO, KC_NO, KC_ENT, KC_LGUI, KC_LSFT, KC_NO,
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
  ),

[_LAYER5] = LAYOUT(
  KC_NO, KC_BSLS, KC_PIPE, KC_DQUO, KC_SPC, KC_ENT, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_NO,
  KC_NO, KC_LCTL, KC_LALT, KC_QUOT, KC_TRNS, KC_NO, KC_CIRC, KC_AMPR, KC_ASTR, KC_LPRN, KC_RPRN, KC_NO,
  KC_NO, KC_LSFT, KC_LGUI, MO(6), KC_NO, KC_NO, KC_GRV, KC_MINS, KC_EQL, KC_LBRC, KC_RCBR, KC_NO,
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
  ),

[_LAYER6] = LAYOUT(
  KC_NO, KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_NO,
  KC_TRNS, CTL_T(KC_F1), ALT_T(KC_F2), KC_F3, KC_TRNS, KC_F5, KC_LEFT, KC_DOWN, KC_UP, KC_RGHT, KC_F11, KC_NO,  
  KC_TRNS, SFT_T(KC_F6), GUI_T(KC_F7), KC_TRNS, KC_F9, KC_F10, KC_HOME, KC_PGDN, KC_PGUP, KC_END, KC_F12, KC_NO,
  KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO, KC_NO
  ),




};
